<Project xmlns="http://schemas.microsoft.com/developer/msbuild/2003">

  <PropertyGroup>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
    <DocumentationMarkdown>$(MSBuildProjectDirectory)\Readme.md</DocumentationMarkdown>
  </PropertyGroup>

  <ItemGroup>
  	<PackageReference Include="Vsxmd" Version="1.4.6">
  		<PrivateAssets>all</PrivateAssets>
  		<IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
  	</PackageReference>
  </ItemGroup>
	
</Project>
